function SaveDivision(CellProps,CType,NetName,NetNameSeg,MedFiltSize,FiltType,...
    BackThresh,WSize,MaxTimeDiff,BlockSize,MinDivArea)

save('CellDivisions.mat','CellProps','-v7.3')
save('Settings.mat','CType','NetName','NetNameSeg','MedFiltSize','FiltType',...
    'BackThresh','WSize','MaxTimeDiff','BlockSize','MinDivArea')
